.TH "/home/alisa/Proga/enum.h" 3 "Thu Aug 25 2022" "Version 6" "QuadrEquation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/alisa/Proga/enum.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTypeOfRoots\fP { \fBNOROOTS\fP, \fBONEROOT\fP, \fBTWOROOTS\fP, \fBIRRROOTS\fP, \fBINFINITE\fP, \fBNOROOTS\fP, \fBONEROOT\fP, \fBTWOROOTS\fP, \fBIRRROOTS\fP, \fBINFINITE\fP }"
.br
.ti -1c
.RI "enum \fBErrCodes\fP { \fBX1NULL\fP = -10, \fBX2NULL\fP, \fBX1EQUX2\fP, \fBAINCVAL\fP, \fBBINCVAL\fP, \fBCINCVAL\fP, \fBDINCVAL\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBErrCodes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIX1NULL \fP\fP
.TP
\fB\fIX2NULL \fP\fP
.TP
\fB\fIX1EQUX2 \fP\fP
.TP
\fB\fIAINCVAL \fP\fP
.TP
\fB\fIBINCVAL \fP\fP
.TP
\fB\fICINCVAL \fP\fP
.TP
\fB\fIDINCVAL \fP\fP
.PP
Definition at line 26 of file enum\&.h\&.
.SS "enum \fBTypeOfRoots\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINOROOTS \fP\fP
.TP
\fB\fIONEROOT \fP\fP
.TP
\fB\fITWOROOTS \fP\fP
.TP
\fB\fIIRRROOTS \fP\fP
.TP
\fB\fIINFINITE \fP\fP
.TP
\fB\fINOROOTS \fP\fP
.TP
\fB\fIONEROOT \fP\fP
.TP
\fB\fITWOROOTS \fP\fP
.TP
\fB\fIIRRROOTS \fP\fP
.TP
\fB\fIINFINITE \fP\fP
.PP
Definition at line 17 of file enum\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for QuadrEquation from the source code\&.
