.TH "/home/alisa/Proga/SolvEqu.h" 3 "Thu Aug 25 2022" "Version 6" "QuadrEquation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/alisa/Proga/SolvEqu.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBiszero\fP (double a)"
.br
.ti -1c
.RI "double \fBdiscriminant\fP (double a, double b, double c)"
.br
.ti -1c
.RI "int \fBsolve_line_case\fP (double b, double c, double *x1)"
.br
.ti -1c
.RI "int \fBsolve_quad_case\fP (double a, double b, double c, double *x1, double *x2)"
.br
.ti -1c
.RI "int \fBsolution\fP (double a, double b, double c, double *x1, double *x2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double discriminant (double a, double b, double c)"

.PP
Definition at line 14 of file SolvEqu\&.cpp\&.
.SS "int iszero (double a)"

.PP
Definition at line 24 of file copy\&.cpp\&.
.SS "int solution (double a, double b, double c, double * x1, double * x2)"

.PP
Definition at line 65 of file copy\&.cpp\&.
.SS "int solve_line_case (double b, double c, double * x1)"

.PP
Definition at line 19 of file SolvEqu\&.cpp\&.
.SS "int solve_quad_case (double a, double b, double c, double * x1, double * x2)"

.PP
Definition at line 59 of file SolvEqu\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for QuadrEquation from the source code\&.
