.TH "io.h" 3 "Thu Aug 25 2022" "Version 7" "QuadEqu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io.h \- reading user's coefficients and writing the result  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinput\fP (double *a, double *b, double *c)"
.br
.ti -1c
.RI "void \fBoutput\fP (\fBTypeOfRoots\fP n, double x1, double x2)"
.br
.ti -1c
.RI "void \fBbuff_clean\fP ()"
.br
.ti -1c
.RI "void \fBprint_err_msg\fP (\fBErrCodes\fP err_code)"
.br
.in -1c
.SH "Detailed Description"
.PP 
reading user's coefficients and writing the result 


.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-08-25
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBio\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void buff_clean ()"

.PP
Definition at line 7 of file io\&.cpp\&.
.SS "void input (double * a, double * b, double * c)"

.PP
Definition at line 30 of file copy\&.cpp\&.
.SS "void output (\fBTypeOfRoots\fP n, double x1, double x2)"

.PP
Definition at line 95 of file copy\&.cpp\&.
.SS "void print_err_msg (\fBErrCodes\fP err_code)"

.PP
Definition at line 53 of file io\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for QuadEqu from the source code\&.
