.TH "temp.cpp" 3 "Thu Aug 25 2022" "Version 7" "QuadEqu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
temp.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintReshetka\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void printReshetka ()"

.PP
Definition at line 4 of file temp\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for QuadEqu from the source code\&.
