.TH "temp.h" 3 "Thu Aug 25 2022" "Version 7" "QuadEqu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
temp.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinput\fP (double *a, double *b, double *c)"
.br
.ti -1c
.RI "void \fBoutput\fP (\fBTypeOfRoots\fP n, double x1, double x2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void input (double * a, double * b, double * c)"

.PP
Definition at line 30 of file copy\&.cpp\&.
.SS "void output (\fBTypeOfRoots\fP n, double x1, double x2)"

.PP
Definition at line 95 of file copy\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for QuadEqu from the source code\&.
