.TH "test.cpp" 3 "Thu Aug 25 2022" "Version 7" "QuadEqu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.cpp \- testing of functions  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'enum\&.h'\fP
.br
\fC#include 'SolvEqu\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_solv_equ\fP ()"
.br
.RI "testing function "
.in -1c
.SH "Detailed Description"
.PP 
testing of functions 


.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-08-25
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBtest\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void test_solv_equ ()"

.PP
testing function 
.PP
Definition at line 21 of file test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for QuadEqu from the source code\&.
